name: isttc
dependencies:
  - python
  - pip
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scipy
  - jupyter          
  - statsmodels      
  - scikit-learn
  - pip:
      - git+https://github.com/roxana-zeraati/abcTau.git